### ISSUE TITLE
安装完插件后文件移动不了

### ISSUE THREAD

**Issue by 880634** [TimmyOVO/CopyToFinder#1]
如题：我发现使用剪切功能之后，文件并没有如预期那样移动到另一个文件夹，而是直接复制了文件，禁用插件之后文件剪切功能就正常了，希望作者修复。

**Comment by 880634** [comment]
![](https://user-images.githubusercontent.com/24937241/107932742-dc8fa880-6fb8-11eb-8c1a-72bf05a78015.png)

**Comment by TimmyOVO** [comment]
新的版本应该已经修复了，是否能试一下呢

**Comment by 880634** [comment]
![](https://user-images.githubusercontent.com/24937241/108016859-76edfb80-704e-11eb-9ed7-a2f8775bb2ec.png)

**Comment by 880634** [comment]
我用的是 1.6 版本，但是我看到你这边有提交更新，但是还没有审核通过，能否直接提供一下最新的安装包给我呢？我来做一下测试有没有问题。

**Comment by TimmyOVO** [comment]
[github release](https://github.com/TimmyOVO/CopyToFinder/releases)

**Comment by 880634** [comment]
可以了，多谢作者。

**Comment by 880634** [comment]
作者大大，发现一个新问题，就是无法剪切文件到 Finder 上

**Comment by TimmyOVO** [comment]
Mac的剪切逻辑是统一先复制，粘贴又分为剪切粘贴，和粘贴
使用Option+Command+V是剪切粘贴
使用Command+V是粘贴
所以和系统是一样的逻辑
在ide里应该只有复制可以粘贴或者剪切到finder里

**Comment by 880634** [comment]
我就是用剪切文件，然后在 Finder 上面无法粘贴，使用复制功能是可以粘贴的，但是剪切功能是不行的，作者大大能兼容一下么

**Comment by TimmyOVO** [comment]
osx系统的逻辑是没有先剪切后粘贴的。
osx系统的逻辑是先复制再剪切过去或者粘贴过去。

**Comment by 880634** [comment]
但是我就是想用 Studio 自带的剪切过去的咋办？

**Comment by TimmyOVO** [comment]
那就没有办法了

**Comment by 880634** [comment]
一定有办法的，作者大大想想办法啊

**Comment by getActivity** [comment]
https://plugins.jetbrains.com/plugin/13517-copytofinder

**Comment by 880634** [comment]
https://plugins.jetbrains.com/plugin/13517-copytofinder

**Comment by 880634** [comment]
作者大大，这个插件在 IDEA 官网上还是 1.6 的版本，是不是审核失败了
